"""
Real-time spread monitoring and signal generation.

Monitors the price spreads of cointegrated pairs and generates
trading signals based on z-score thresholds.
"""

import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from enum import Enum

from ..utils.config import get_config
from ..utils.logger import setup_logger
from ..data.fetcher import DataFetcher
from ..data.database import Database

logger = setup_logger(__name__)


class SignalType(Enum):
    """Types of trading signals."""
    LONG_SPREAD = "long_spread"  # Buy stock1, sell stock2
    SHORT_SPREAD = "short_spread"  # Sell stock1, buy stock2
    EXIT_LONG = "exit_long"
    EXIT_SHORT = "exit_short"
    STOP_LOSS = "stop_loss"
    NO_SIGNAL = "no_signal"


@dataclass
class SpreadState:
    """Current state of a pair's spread."""
    symbol1: str
    symbol2: str
    hedge_ratio: float
    current_spread: float
    zscore: float
    mean_spread: float
    std_spread: float
    last_updated: datetime
    signal: SignalType = SignalType.NO_SIGNAL
    position_type: Optional[str] = None  # 'long' or 'short' or None


@dataclass
class TradingSignal:
    """A trading signal generated by the monitor."""
    timestamp: datetime
    symbol1: str
    symbol2: str
    signal_type: SignalType
    zscore: float
    spread: float
    price1: float
    price2: float
    hedge_ratio: float
    pair_id: int


class SpreadMonitor:
    """
    Monitors spreads for cointegrated pairs and generates signals.

    The monitor:
    1. Fetches latest prices for tracked pairs
    2. Calculates current spread and z-score
    3. Compares against entry/exit thresholds
    4. Generates appropriate trading signals
    """

    def __init__(self):
        self.config = get_config()
        self.fetcher = DataFetcher()
        self.db = Database()

        # Monitor parameters
        self.entry_threshold = self.config.get("monitor.entry_threshold", 2.0)
        self.exit_threshold = self.config.get("monitor.exit_threshold", 0.5)
        self.stop_loss_threshold = self.config.get("monitor.stop_loss_threshold", 4.0)
        self.spread_window = self.config.get("monitor.spread_window", 60)

        # Track current state for all pairs
        self.pair_states: Dict[int, SpreadState] = {}

        # Track historical spreads for rolling calculations
        self.spread_history: Dict[int, pd.Series] = {}

    def initialize_pairs(self) -> None:
        """Load active pairs from database and initialize monitoring."""
        active_pairs = self.db.get_active_pairs()
        logger.info(f"Initializing monitoring for {len(active_pairs)} pairs")

        for pair in active_pairs:
            pair_id = pair['id']
            self.pair_states[pair_id] = SpreadState(
                symbol1=pair['symbol1'],
                symbol2=pair['symbol2'],
                hedge_ratio=pair['hedge_ratio'],
                current_spread=pair['mean_spread'],
                zscore=0.0,
                mean_spread=pair['mean_spread'],
                std_spread=pair['std_spread'],
                last_updated=datetime.now(),
                signal=SignalType.NO_SIGNAL,
                position_type=None
            )

            # Initialize spread history
            self.spread_history[pair_id] = pd.Series(dtype=float)

        # Load historical data to calculate initial rolling statistics
        self._load_historical_spreads()

    def _load_historical_spreads(self) -> None:
        """Load historical spread data for rolling calculations."""
        if not self.pair_states:
            return

        # Get all unique symbols
        symbols = set()
        for state in self.pair_states.values():
            symbols.add(state.symbol1)
            symbols.add(state.symbol2)

        # Fetch recent historical data
        lookback_days = self.spread_window * 2
        end_date = datetime.now().strftime("%Y-%m-%d")
        start_date = (datetime.now() - timedelta(days=lookback_days)).strftime("%Y-%m-%d")

        try:
            prices = self.fetcher.fetch_historical_data(
                list(symbols),
                start_date=start_date,
                end_date=end_date
            )

            # Calculate historical spreads for each pair
            for pair_id, state in self.pair_states.items():
                if state.symbol1 in prices.columns and state.symbol2 in prices.columns:
                    spread = prices[state.symbol1] - state.hedge_ratio * prices[state.symbol2]
                    self.spread_history[pair_id] = spread.tail(self.spread_window)

                    # Update mean and std with rolling data
                    state.mean_spread = spread.mean()
                    state.std_spread = spread.std()

        except Exception as e:
            logger.error(f"Error loading historical spreads: {e}")

    def update_prices(self, prices: Optional[Dict[str, float]] = None) -> List[TradingSignal]:
        """
        Update prices and check for trading signals.

        Args:
            prices: Dict of symbol -> current price (if None, fetches latest)

        Returns:
            List of trading signals generated
        """
        if prices is None:
            # Fetch latest prices for all symbols
            symbols = set()
            for state in self.pair_states.values():
                symbols.add(state.symbol1)
                symbols.add(state.symbol2)
            prices = self.fetcher.fetch_latest_prices(list(symbols))

        signals = []

        for pair_id, state in self.pair_states.items():
            if state.symbol1 not in prices or state.symbol2 not in prices:
                logger.warning(f"Missing price data for {state.symbol1}-{state.symbol2}")
                continue

            price1 = prices[state.symbol1]
            price2 = prices[state.symbol2]

            # Calculate current spread
            current_spread = price1 - state.hedge_ratio * price2

            # Update spread history
            if pair_id in self.spread_history:
                self.spread_history[pair_id] = pd.concat([
                    self.spread_history[pair_id],
                    pd.Series([current_spread])
                ]).tail(self.spread_window)

                # Recalculate rolling mean and std
                state.mean_spread = self.spread_history[pair_id].mean()
                state.std_spread = self.spread_history[pair_id].std()

            # Calculate z-score
            if state.std_spread > 0:
                zscore = (current_spread - state.mean_spread) / state.std_spread
            else:
                zscore = 0.0

            # Update state
            state.current_spread = current_spread
            state.zscore = zscore
            state.last_updated = datetime.now()

            # Generate signal based on z-score and current position
            signal = self._generate_signal(state, pair_id, price1, price2)
            if signal:
                signals.append(signal)
                state.signal = signal.signal_type

                # Log the signal
                logger.info(
                    f"Signal: {signal.signal_type.value} for {state.symbol1}-{state.symbol2} "
                    f"(z-score: {zscore:.2f})"
                )

                # Save signal to database
                self.db.save_signal(
                    pair_id=pair_id,
                    symbol1=state.symbol1,
                    symbol2=state.symbol2,
                    signal_type=signal.signal_type.value,
                    zscore=zscore,
                    spread=current_spread
                )

        return signals

    def _generate_signal(
        self,
        state: SpreadState,
        pair_id: int,
        price1: float,
        price2: float
    ) -> Optional[TradingSignal]:
        """
        Generate a trading signal based on current spread state.

        Trading logic:
        - Entry: When z-score crosses beyond entry threshold
        - Exit: When z-score reverts back toward mean
        - Stop Loss: When z-score exceeds stop loss threshold
        """
        zscore = state.zscore

        # Check for stop loss first
        if state.position_type is not None:
            if abs(zscore) > self.stop_loss_threshold:
                return TradingSignal(
                    timestamp=datetime.now(),
                    symbol1=state.symbol1,
                    symbol2=state.symbol2,
                    signal_type=SignalType.STOP_LOSS,
                    zscore=zscore,
                    spread=state.current_spread,
                    price1=price1,
                    price2=price2,
                    hedge_ratio=state.hedge_ratio,
                    pair_id=pair_id
                )

        # Check exit conditions if we have a position
        if state.position_type == "long":
            # Exit long when z-score returns to near mean
            if zscore > -self.exit_threshold:
                return TradingSignal(
                    timestamp=datetime.now(),
                    symbol1=state.symbol1,
                    symbol2=state.symbol2,
                    signal_type=SignalType.EXIT_LONG,
                    zscore=zscore,
                    spread=state.current_spread,
                    price1=price1,
                    price2=price2,
                    hedge_ratio=state.hedge_ratio,
                    pair_id=pair_id
                )

        elif state.position_type == "short":
            # Exit short when z-score returns to near mean
            if zscore < self.exit_threshold:
                return TradingSignal(
                    timestamp=datetime.now(),
                    symbol1=state.symbol1,
                    symbol2=state.symbol2,
                    signal_type=SignalType.EXIT_SHORT,
                    zscore=zscore,
                    spread=state.current_spread,
                    price1=price1,
                    price2=price2,
                    hedge_ratio=state.hedge_ratio,
                    pair_id=pair_id
                )

        # Check entry conditions if no position
        if state.position_type is None:
            # Long spread: spread is too low (negative z-score)
            # Strategy: buy stock1, sell stock2
            if zscore < -self.entry_threshold:
                return TradingSignal(
                    timestamp=datetime.now(),
                    symbol1=state.symbol1,
                    symbol2=state.symbol2,
                    signal_type=SignalType.LONG_SPREAD,
                    zscore=zscore,
                    spread=state.current_spread,
                    price1=price1,
                    price2=price2,
                    hedge_ratio=state.hedge_ratio,
                    pair_id=pair_id
                )

            # Short spread: spread is too high (positive z-score)
            # Strategy: sell stock1, buy stock2
            elif zscore > self.entry_threshold:
                return TradingSignal(
                    timestamp=datetime.now(),
                    symbol1=state.symbol1,
                    symbol2=state.symbol2,
                    signal_type=SignalType.SHORT_SPREAD,
                    zscore=zscore,
                    spread=state.current_spread,
                    price1=price1,
                    price2=price2,
                    hedge_ratio=state.hedge_ratio,
                    pair_id=pair_id
                )

        return None

    def update_position_state(self, pair_id: int, position_type: Optional[str]) -> None:
        """Update the position state for a pair after trade execution."""
        if pair_id in self.pair_states:
            self.pair_states[pair_id].position_type = position_type

    def get_all_states(self) -> List[SpreadState]:
        """Get current state of all monitored pairs."""
        return list(self.pair_states.values())

    def get_pair_state(self, pair_id: int) -> Optional[SpreadState]:
        """Get state for a specific pair."""
        return self.pair_states.get(pair_id)

    def get_summary(self) -> Dict[str, Any]:
        """Get a summary of current monitoring state."""
        if not self.pair_states:
            return {"status": "No pairs being monitored"}

        zscores = [state.zscore for state in self.pair_states.values()]
        positions = sum(1 for s in self.pair_states.values() if s.position_type is not None)

        return {
            "num_pairs": len(self.pair_states),
            "num_positions": positions,
            "avg_zscore": np.mean(np.abs(zscores)),
            "max_zscore": np.max(np.abs(zscores)),
            "pairs_above_entry": sum(1 for z in zscores if abs(z) > self.entry_threshold),
            "last_updated": max(s.last_updated for s in self.pair_states.values())
        }
